const Modifier = {
  Big: "Big",
  Blue: "Blue",
  Red: "Red",
  Tall: "Tall",
  White: "White",
  Creekside: "Creekside",
  Peakview: "Peakview",
  Snowy: "Snowy",
  Rocky: "Rocky",
  Aspen: "Aspen",
  Breckenridge: "Breckenridge",
  Denver: "Denver",
  Milehigh: "Mile-High",
  Silver: "Silver",
  Winter: "Winter",
  Pine: "Pine",
  Jacks: "Jack's",
  Bobs: "Bob's",
  Smiths: "Smith's",
};

const Noun = {
  Mountain: "Mountain",
  River: "River",
  Rock: "Rock",
  Treeline: "Treeline",
  Deer: "Deer",
  Elk: "Elk",
  Sky: "Sky",
  Bison: "Bison",
  Roots: "Roots",
  Moose: "Moose",
  Ridge: "Ridge",
  Pass: "Pass",
  Lake: "Lake",
  Beaver: "Beaver",
  Trout: "Trout",
  Bass: "Bass",
};

const BusinessType = {
  Grill: "Grill",
  Cafe: "Cafe",
  Restaurant: "Restaurant",
  Diner: "Diner",
  Bar: "Bar",
  Grocery: "Grocery",
  Station: "Station",
  Convenience: "Convenience",
  Sports: "Sports",
  Shoppe: "Shoppe",
  Boutique: "Boutique",
  Park: "Park",
  Inn: "Inn",
  Chophouse: "Chophouse",
};

export { Modifier, Noun, BusinessType };
